name: custom_artifact
on: push
jobs:
  job1:
    name: Build custom artifact
    env:
      My_Artifact: myartifact
    runs-on: ubuntu-latest
    steps:
      -  name: checkout
         uses: actions/checkout@v2
      -  name: upload artifact
         uses: actions/upload-artifact@v2
         with:
           name: ${{env.My_Artifact}}
           path: .
           

  
